title: Thiyagarajan K
author: Thiyagarajan K
email: contact@thiyagarajan.in
description: > # this means to ignore newlines until "show_exerpts:"
  IT Ops Engineer - Specialized in On-premises and Cloud Operations and Management, Product delivery, Maintenance, Technical Support & Consultancy.
  
#theme: plainwhite-jekyll
remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: Thiyagarajan Karuppaiah
  tagline: Techi. Athlete
  date_format: "%b %-d, %Y"

  social_links:
    twitter: 2mrt
    github:  thiyaguin
    linkedIn: in/2thiyagu

markdown: kramdown
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-redirect-from
